### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by GeeYangML** [MLMonkATGY/Calvinn-Alex-research-2024#2]
1. What benchmark can we do now ?
2. What metric are we using ?

**Comment by Calvinnncy97** [comment]
For metrics, we will mainly be using 

Precision @ top-k 
Recall @ top-k 
F1 @ top-k


LLM evaluation is KIV. For now, we want a controlled set of high quality labels for evaluation to ensure that we are doing the right thing.
